#!/bin/sh -x

git pull
composer install
git submodule init
git submodule update

cd client
npm install
npm run-script build
cd ..

mkdir -p css
mkdir -p js

cp client/dist/bundle.css css/bundle.css
cp client/dist/bundle.js js/bundle.js
cp client/dist/dobinning.worker.js js/dobinning.worker.js
cp client/dist/docluster.worker.js js/docluster.worker.js
