#!/bin/sh +x

git pull
composer install
git submodule init
git submodule update

cd client
# npm install
cd ..

mkdir -p css
mkdir -p js

cp client/dist/bundle.css css/bundle.css
cp client/dist/bundle.js js/bundle.js
